### PR TITLE
Convert root_dir passed to zypper/rpm --root to absolute path

### PR DESCRIPTION
**Pull request by Conan-Kudo**
Zypper on openSUSE 42.2 barfs when passed in root_dir as an argument for `--root` because it is always a relative path and Zypper doesn't like that. So, we convert it to an absolute path.

RPM also requires a similar change.

P.S.: @msrex sends his regards (we spent some time tracking this down while building images on openSUSE Leap 42.2)

Changes proposed in this pull request:
* Use `os.path.abspath()` on `root_dir` being passed to `zypper --root`
* Use `os.path.abspath()` on `root_dir` being passed to `rpm --root`

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@davidcassany There is no way for the user to provide paths for `--root`. These things that I'm forcing the paths to become absolute are generated by KIWI itself. Frankly, we're wondering how in the world it ever worked since we spent four hours debugging this to get it to work, leading to this PR and #272.

I don't know how to fix the unit-tests for either PR.

**Comment by davidcassany** [comment]
@Conan-Kudo right, let me make some trials about it, I think that forcing absolute paths for prepare, create or build tasks should be sufficient. 

You using relative paths in the command line, right? Does it work for you if using absolute paths?

**Comment by msrex** [comment]
@davidcassany We used relative paths in the kiwi command line.

**Comment by schaefi** [comment]
It should definitely work with relative and absolute paths, turning any path into its abspath seems a good solution if there are also tests covering both cases

**Comment by davidcassany** [comment]
@scahefi right, then I would go for turning relative paths to absolute just at the time of parsing the user input flags. I mean inside `kiwi/tasks/*` to make sure they are absolute when they are passed to `kiwi/system/*` classes or any other class that actually performs the work. 

What you think?

**Comment by schaefi** [comment]
sounds good to me :+1:

**Comment by msrex** [comment]
I experimented with building yum-based images. There we have the same issue with absolute paths being required for --root.

**Comment by davidcassany** [comment]
@schaefi ok, I am on it. 

@Conan-Kudo, @msrex with you permit I'll provide a patch for that as discussed above, this way it will be also easier to make the unit tests.

**Comment by schaefi** [comment]
@msrex yes the issue should be the same for all targets, David will create a proper fix. Handling that at the entry point level will most probably also fix #272

**Comment by Conan-Kudo** [comment]
@schaefi Sounds good to me.

**Pull request closed without merging**
