### PR TITLE
Fixup repository setup with no type declaration

### PR DESCRIPTION
**Pull request by schaefi**
The type attribute in a repository section is optional, if not
specified the zypper add_repo code throws a KiwiRepoTypeUnknown
exception. However this is not needed because the repository
could be added without a type declaration in order to let zypper
auto detect the repository type

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Zypper's autodetection of repo types doesn't work. It always falls back to type "NONE", which makes Zypper behave oddly.

**Comment by Conan-Kudo** [comment]
Yum and DNF only support `type=rpm-md`, anything else won't work.

**Comment by schaefi** [comment]
well --type is only an option for zypper, if it can't cope correctly with it, it should be fixed. The changes here are basically to stay compatible with the schema which allowed to leave out the type attribute since a very long time. People actually use zypper addrepo without a type quite often, thus I don't want to force them into a type declaration even though we recommend to specify one

**Comment by schaefi** [comment]
> Yum and DNF only support type=rpm-md, anything else won't work.

right and the repo_type parameter is therefore not used in the implementation and should not have a value

**Comment by Conan-Kudo** [comment]
> People actually use zypper addrepo without a type quite often, thus I don't want to force them into a type declaration even though we recommend to specify one

I agree it should work, it's just that since openSUSE 13.2, it's been half broken. :(

**Comment by schaefi** [comment]
man you are so right, I just did a short test in 13.2, Leap42.1, Leap42.2 and even Factory and it's all broken :( ok I think I'll revert this

**Comment by Conan-Kudo** [comment]
@schaefi It bit me when I first started supporting openSUSE for the Datto Linux Backup Agent, I have no idea why this isn't fixed.

The fedora-repos package for Fedora 26+ also got adjusted to include `type=` because Zypper broke everyone else by putting `type=NONE`. :(

**Pull request closed without merging**
