### PR TITLE
Refactor into subpackage to fix #23

### LINKED ISSUE #23: Idea: Use more Subpackages
Again just one of my crazy ideas. :grin:  To be honest, I'm not 100% sure if this is really a good idea, so treat it as non-important and something for the future. Feel free to close it. :smile:

The basic idea is to use more (sub)packages. Packages in Python are directories which contains a `__init__.py` file.

For example, you have lots of `filesystem_*.py` files. The same applies to `bootloader*.py`, `container*.py`, and others. For me, that cries for refactoring it into (sub)packages. 

Let's assume for the moment, the idea has any value and we want to refactor all the `filesystem*.py` files. In that case, we could do this:

1. Create the directory `filesystems` (or use the singular form, doesn't matter for the time being).
2. Move `filesystem.py` to `filesystems/__init__.py` (or better leave `__init__.py` empty and use a different name).
3. Move the other `filesystem_<NAME>.py` files to `filesystems/<NAME>.py`.

There you have it, a `filesystems` (sub)package!  :-)

What do we gain?

* The `kiwi` directory doesn't look so crowded after the restructuring.
* Maybe a little bit easier to type ("Readability counts"¹).
* Creates a `filesystems` "namespace" instead of packing everything into a file ("Namespaces are one honking great idea -- let's do more of those!"¹)
* No special file naming schema is needed, just add everything under `filesystems` and you're done.
* Probably easier to collect all the relevant files under the `filesystems` directory (think of a plugin systems).
* Easier to extend.

¹ cited from `import this`

Disadvantages:
* All(?) tests need to be examined and probably rewritten
* Problem with circular dependencies? I don't know.
* Other things...?

Ok, that's all. ;-)

### PR DESCRIPTION
**Pull request by tomschr**
Hint: @schaefi please apply the other PR first, before using this one.

This is quite a heavy PR. :grin: Please check carefully, although I've run the test suite several times.

## Changes
* Refactor `archive_*.py` -> `archive` subpackage
* Refactor `partitioner_*.py` -> `partitioner` subpackage
* Refactor `package_manager_*.py` -> `package_manager` subpackage
* Refactor `bootloader_config*.py` -> `bootloader/config` subpackage
* Refactor `bootloader_template*.py` -> `bootloader/template` subpackage
* Refactor `bootloader_install*.py` -> `bootloader/install` subpackage
* Refactor `repository*.py` -> `repository` subpackage
* Refactor `filesystem*.py` -> `filesystem` subpackage
* Refactor `dist_*.py` -> `dist/dformat` subpackage
  The name `dformat` as package name is needed to avoid any name conflicts with the built-in function `format()`.
* Refactor `volume_manager*.py` -> `volume_manager` subpackage
* Refactor `boot_image*.py` -> `boot/image` subpackage

I've tried to be consistent. For example, `filesystem.py` is moved to `filesystem/__init__.py` as no code changes are needed when importing `filesystem`. The `filesystem_<X>.py` files are renamed to `filesystem/<X>.py` without the `filesystem_` suffix. The same rules apply for other files.

Sometimes subsubpackages arise, but I hope this doesn't introduce any problems.

Refactoring went surprisingly well, thanks to your extensive test suite. :+1: It helped me to spot missing parts very quickly.

Maybe other files can be refactored as well, but I leave it in this state for the time being.

### CODE REVIEW

**Comment by schaefi** [comment]
wow are you crazy :smile: I told you not to work on the weekend :smile: 
Just kidding this is great work and I'm glad that my tests were useful for the this heavy changes

I'm going to merge it and do some test builds

**Comment by tomschr** [comment]
> wow are you crazy :smile: I told you not to work on the weekend :smile:

I couldn't resist. :laughing:  Actually, it was during the week, I just finish it on Saturday (wasn't a big deal).


> I'm going to merge it and do some test builds

Great, thanks a lot! Yes, please create some test builds. Hope I didn't break too much.

**Comment by schaefi** [comment]
I'm going to test it and will also change the structure a little bit, builder and containers should have their own namespace, there should also be storage. Give me a day to continue what you have started. It's really worth the effort

Thanks

**Comment by schaefi** [comment]
ok I'm done with my additions. Could you have a short look ? Thanks

**Comment by tomschr** [comment]
Cool! This is really great. :+1:

As I don't know the code as much as you do, my part was only a kind of "renaming". The structure looks much better now. Plus the unfortunate `dformat` package name disappeared. Great!

I've looked over you code but I couldn't spot any problems so far (need to go to a meeting so it was only a quick look).

Great work Marcus, well done!

**Pull request merged**
