### PR TITLE
Add docstrings for Cli class

### PR DESCRIPTION
**Pull request by schaefi**
Add docstrings for Cli class
    
References Issue #49

### CODE REVIEW

**Comment by schaefi** [comment]
@tomschr I have added the basic autodoc structure and tested the generated result

What do you think ?

**Comment by schaefi** [comment]
I'm not sure if we really need the Methods references as part of the class docstring, however it's nice to see them as a reference list

**Comment by tomschr** [comment]
@schaefi Just had a quick look before going back to my workshop... ;)

Actually, after our discussion yesterday I've started also to research a bit about this topic. I'm sorry if I didn't tell you earlier, but it seems most of the tedious work can be done (semi-)automatically. I'm thinking about the [`sphinx-apidoc`](http://www.sphinx-doc.org/en/stable/man/sphinx-apidoc.html)  and the `sphinx-autogen` scripts.

Both seem to do similar tasks. Either way, I guess, the way to go is to use one of these scripts and integrate it into `tox.ini`.

Bascially, the idea is to run one of the scripts over your KIWI Python sources. This creates "stub" files which can then be included into your API reference. I've did it before and it works "somehow".

Unfortunately, I haven't found a good page which explains all the differences, the pros and cons, and what else is needed. Most pages seems a bit outdated on this topic.

Your files look really great and I'm very happy you did such an awesome work! :+1:  It seems to me, most of the work can be done with one of the scripts above.

I would recommend to read http://www.sphinx-doc.org/en/stable/ext/autosummary.html this gives a good overview of the semi-automated way. Hope this helps!

**Comment by schaefi** [comment]
Hi,

>    Your files look really great and I'm very happy you did such an awesome
>    work! :+1: It seems to me, most of the work can be done with one of the
>    scripts above.

:) I have used the scripts, see the commit message:

    Create Initial autodoc structure
    
    Called 'sphinx-apidoc -o source/api ../kiwi'

I have not integrated that into tox, though. My intention is to
first agree on the format of the docstrings to fit well into the
generated documentation according to your thoughts

So what do you think about the docstring format as used in cli.py

* ist that ok, description plus public attributes, plus list of methods ?
* could we live without the method list ?

Thanks

**Comment by tomschr** [comment]
> :) I have used the scripts, see the commit message:

Ok, right. I missed that part, sorry. Note to myself: Don't comment on GH issues before going to a workshop. :grimacing: 

> So what do you think about the docstring format as used in cli.py 
> * is that ok, description plus public attributes, plus list of methods ?

I think this goes a bit over the top if everything is stuffed into a docstring. :) 
I probably failed to address it from my last comment, but usually you create the *description* in your docstring. The list of all methods appears in the RST files (be it manually or automatically created).

That way you don't have too much "doc code" inside your docstrings which just blows up your size.

At least that was my understanding when dealing with this topic. Maybe I'm wrong.

> * could we live without the method list ?

Good question. I think we should answer one of the following questions first:

1. Why do we need it?
2. What purpose does/should it fulfill?

For me (1) would be to have a good API documentation which can be searched and viewed. Help can be "consumed" through the interactive Python shell or via HTML. That depends on what someone prefers.

What the purpose is answers question (2): the purpose (at least IMHO) is to help contributors which works with the source code to find their way through it.

To cut a long story, from a contributors perspective, it would be probably good to have a list of methods and their arguments---at least, when someone is reading the HTML page. However, the methods can be automatically created and doesn't have to appear inside the class docstring.

Let me try it out and I can show you my idea. If you are fine with it, I can commit some of my changes into your branch. Would that be ok?

**Comment by schaefi** [comment]
Thanks Tom, I have included your doc suggestions.

Regarding the docstrings, I think we don't need an extra list of methods, this is documented automatically pretty nicely. I was reading through the generated results and found all information from the classes without extra hyper references

**Pull request merged**
