### PR TITLE
Dracut kiwi dump

### PR DESCRIPTION
**Pull request by schaefi**
Implementation of dracut kiwi-dump module
    
Provide the capabilities of the oem install code as dracut module. The implementation covers the result   of the installiso="true" configuration. Installation from remote sources still needs to be done and will    follow in an extra pull request. This addresses Issue #576

### CODE REVIEW

**Comment by schaefi** [comment]
In order to activate dracut for oem one explicitly has to state

```xml
<type image="oem" .... initrd_system="dracut"/>
```

**Comment by schaefi** [comment]
Code for iso installer is provided with the sub package dracut-kiwi-oem-dump. Therefore the image description also must state:

```xml
<package name="dracut-kiwi-oem-dump"/>
```

An appropriate runtime check for this condition is still missing and will be provided next

**Comment by schaefi** [comment]
Thanks for testing it. If you don't see severe issue I will continue to look into the network support and fill in the open TODO gaps. Thus there might be another round of review for this one :) Thanks

**Comment by davidcassany** [comment]
Sure, so far so good, feel free to ask me tests/review/help/opinion at any time :) Later today if I have some time I'll do some tests with non openSUSE/SUSE distros.

**Comment by schaefi** [comment]
@davidcassany ok I'm done with the remote install part :)

If you would like to test it here is what I did:

1. You need a proper dnsmasq setup like this one

```
# Don't function as a DNS server:
port=0

# Log lots of extra information about DHCP transactions.
log-dhcp

# Set the root directory for files available via FTP.
tftp-root=/srv/tftpboot

# The boot filename, Server name, Server Ip Address
dhcp-boot=pxelinux.0,,192.168.100.16

# Disable re-use of the DHCP servername and filename fields as extra
# option space. That's to avoid confusing some old or broken DHCP clients.
dhcp-no-override

# PXE menu.  The first part is the text displayed to the user.  The second is the timeout, in seconds.
pxe-prompt="Booting FOG Client", 1

# The known types are x86PC, PC98, IA64_EFI, Alpha, Arc_x86,
# Intel_Lean_Client, IA32_EFI, BC_EFI, Xscale_EFI and X86-64_EFI
# This option is first and will be the default if there is no input from the user.
pxe-service=X86PC, "Boot to FOG", pxelinux.0
pxe-service=X86-64_EFI, "Boot to FOG UEFI", ipxe
pxe-service=BC_EFI, "Boot to FOG UEFI PXE-BC", ipxe

dhcp-range=192.168.100.16,proxy
    
```

2. you need a working tftp server, I did not use dnsmasq's one, maybe that would work too
    So I have atftp installed and running

```
systemctl start atftpd.socket
systemctl start atftpd
```

3. Next build the image with ```installpxe="true"```

4. The result tarball contains:

LimeJeOS-Leap-42.3.initrd
LimeJeOS-Leap-42.3.kernel
LimeJeOS-Leap-42.3.md5
LimeJeOS-Leap-42.3.xz

which I put in /srv/tftpboot/image

It also contains:

pxeboot.kernel
pxeboot.initrd

which I put in /srv/tftpboot/boot as files ```initrd`` and ```linux```

5. you need a proper pxe boot config /srv/tftpboot/pxelinux.cfg/default

```
DEFAULT KIWI-Boot

LABEL KIWI-Boot
        kernel boot/linux
        append initrd=boot/initrd splash=silent vga=0x317 rd.kiwi.install.pxe rd.kiwi.install.image=tftp://192.168.100.16/image/LimeJeOS-Leap-42.3.xz rd.kiwi.debug rd.debug

LABEL Local-Boot
        localboot 0
```

6. and last but not least the pxelinux.0 loader from syslinux but I think you know about that

**Comment by davidcassany** [comment]
@schaefi awsome, I will test it, hopefully today. Now I am reading `dmsquash-live` dracut module and `kiwi-live` module, pretty interesting reading :)

**Comment by schaefi** [comment]
dmsquash-live is hard to read... as usual when code handles device mapper, my head is always spinning with devmapper, that thing is crazy cool and hard to do it right :)

**Comment by schaefi** [comment]
Once we have moved all historical boot code all the rest is covered by shellcheck which is really nice. I'm happy that soon we will have all shell code under control like we do with the python code

**Comment by schaefi** [comment]
@davidcassany I'll give this one a last test round today and will merge unless there are concerns

**Comment by davidcassany** [comment]
sure, I'm currently giving it a try

**Comment by schaefi** [comment]
I found one case in which systemd starts a rescue shell because a mount target is busy. I don't think it's because of the dump code but probably the repart code causes a udev event which mounts the target. I'll check that

**Comment by schaefi** [comment]
Found the problem and will add one additional commit next

**Comment by davidcassany** [comment]
All right, sorry it is taking me a little longer than expected to make some successful test, now I will test your PXE server receipt, since the VMX server I have fails in someway to deliver the image to download.

**Comment by schaefi** [comment]
yeah for pxe testing I also had several iterations to come to a speedy setup. dnsmasq plus atftp works well for me and does not conflict with other services you might have in your network (if configured as shown above). qemu -boot n picks up the right server and you can test all on one machine

**Comment by davidcassany** [comment]
Finally I managed to successfully test the pxe boot for oem installation. I works fine, your last commit was the key :+1 then I just had to install some missing packages into the image and it worked fine. I managed to boot using your dnsmasq configuration receipt and also using the libvirt network configuration I used to use before, which is great, I can pxe boot using the same config I used to use previously.

Ready to merge from my side :)

**Comment by schaefi** [comment]
totally great, thanks for testing. I'll merge :)

**Pull request merged**
