### PR TITLE
Reactivate device mappings after repart. Fixes #645

### LINKED ISSUE #645: kiwi-repart dracut module looks like it gets interrupted
## Problem description

Installing kiwi-repart and kiwi-dump dracut modules causes Tumbleweed images to not boot and some erratic behavior in Leap 42.3 images (repartition is not done properly)

## Expected behaviour

Tumbleweed images should boot and Leap 42.3 should boot with the appropriate repartition done. Up to now I could trace that installing `dracut-kiwi-oem-repart` and `dracut-kiwi-oem-dump` together causes this issue, intalling only `dracut-kiwi-oem-repart` produces the expected behavior. Looks like there is some sort of wrong interaction with these two modules.

## Steps to reproduce the behaviour

Build the oem image from the kiwi-descriptions (Leap 42.3) or the Tumbleweed image from `build-tests/x86/test-image-oem/`

## OS and Software information
+ KIWI version: 9.13.1
+ Operating system: Leap 42.2
+ OBS version: None

### PR DESCRIPTION
**Pull request by davidcassany**
This commit recreates removed device maps and triggers again
systemd generators in order to adapt again device units to the
new context. Fixes #645

### CODE REVIEW

**Comment by schaefi** [comment]
This looks brilliant :+1: 

you set the wip label, means you are still in testing phase ?

**Comment by davidcassany** [comment]
Oh forgot to press the comment button for the message below... :-P

I am pretty confident this is a good solution, however I am finalizing some more tests. Currently I am having an issue with PXE deploy, but I think it is either by some issue in my env or another unrelated bug, because of this I have included the work in progress label.

@schaefi In fact I would appreciate if you could test this with a PXE deploy

**Comment by schaefi** [comment]
I'll give it a test on Monday, currently software.opensuse.org is also down for maintenance... so no show at the moment :)

**Comment by schaefi** [comment]
I'm now testing an oem pxe deployment with your changes

**Comment by davidcassany** [comment]
Great, thanks much.
I don't think anymore it is an issue of my env, thus should experience the same issues (boot-efi mount fails). It is an odd failure, probably some race issue while trying to mount boot-efi, as it mounts perfectly well in the emergency shell and then continues to boot normally. What I can't figure out at the moment is why it only happens in PXE deployment and how the change I did could have caused this issue.

**Comment by schaefi** [comment]
Hmm, I remember that I saw this in the past too but I can't safely reproduce it. The test right now did not show the problem, all works fine. Regarding the change I also don't see how the efi mount is directly related to the change

...hmm

**Comment by davidcassany** [comment]
Damn, it works for you... hmmm I am rebuilding my tests now from scracth, for both, Leap and Tumbleweed, and see if I can recreate it.

**Comment by schaefi** [comment]
I tested Leap42.3, will try tumbleweed too

**Comment by schaefi** [comment]
ah with tumbleweed I can reproduce the error

**Comment by schaefi** [comment]
oh no wait, forgot to apply your changes

**Comment by schaefi** [comment]
Works great on TW too with your patches :) 

NAME="openSUSE Tumbleweed"
# VERSION="20180302"

**Pull request merged**
