### PR TITLE
kiwi-repart: avoid race between repart and fsck

### LINKED ISSUE #1034: OEM image first boot filesystem resize fails (race condition)
## Problem description
download the trivial centos7 iso from https://build.opensuse.org/package/binaries/home:seife:kiwitest-centos/centos7-iso/images (or use the raw.xz), boot in QEMU with

`qemu-kvm -m 1024 -cdrom CentOS_7-iso.x86_64-0.1.0-Build2.4.install.iso -hda /tmp/img.raw -boot d`

watch it failing sometimes.

It fails even more reliably for me by downloading the raw.xz, then
```
xzcat CentOS_7-iso.x86_64-0.1.0-Build2.4.raw.xz > /tmp/img.raw
truncate -s 100G /tmp/img.raw
qemu-kvm -m 1024 -hda /tmp/img.raw
```
It fails 100% for me in a VMware Workstation 15 Player VM in EFI mode.

This is the relevant part of journal:
```[    6.355182] localhost kernel: ACPI: PCI Interrupt Link [LNKC] enabled at IRQ 11
[    7.245761] localhost kernel: e1000 0000:00:03.0 eth0: (PCI:33MHz:32-bit) 52:54:00:12:34:56
[    7.251794] localhost kernel: e1000 0000:00:03.0 eth0: Intel(R) PRO/1000 Network Connection
[    7.252861] localhost kernel: ata_piix 0000:00:01.1: version 2.13
[    7.259927] localhost kernel: scsi host0: ata_piix
[    7.288537] localhost kernel: scsi host1: ata_piix
[    7.289078] localhost kernel: ata1: PATA max MWDMA2 cmd 0x1f0 ctl 0x3f6 bmdma 0xc040 irq 14
[    7.289611] localhost kernel: ata2: PATA max MWDMA2 cmd 0x170 ctl 0x376 bmdma 0xc048 irq 15
[    7.449579] localhost kernel: ata2.01: NODEV after polling detection
[    7.451243] localhost kernel: ata2.00: ATAPI: QEMU DVD-ROM, 2.5+, max UDMA/100
[    7.459810] localhost kernel: ata1.00: ATA-7: QEMU HARDDISK, 2.5+, max UDMA/100
[    7.460418] localhost kernel: ata1.00: 209715200 sectors, multi 16: LBA48 
[    7.460968] localhost kernel: ata1.01: ATA-7: QEMU HARDDISK, 2.5+, max UDMA/100
[    7.461568] localhost kernel: ata1.01: 204800 sectors, multi 16: LBA48 
[    7.464027] localhost kernel: ata1.00: configured for MWDMA2
[    7.465624] localhost kernel: ata1.01: configured for MWDMA2
[    7.466660] localhost kernel: scsi 0:0:0:0: Direct-Access     ATA      QEMU HARDDISK    2.5+ PQ: 0 ANSI: 5
[    7.467821] localhost kernel: scsi 0:0:1:0: Direct-Access     ATA      QEMU HARDDISK    2.5+ PQ: 0 ANSI: 5
[    7.469967] localhost kernel: ata2.00: configured for MWDMA2
[    7.471741] localhost kernel: scsi 1:0:0:0: CD-ROM            QEMU     QEMU DVD-ROM     2.5+ PQ: 0 ANSI: 5
[    7.613351] localhost kernel: sd 0:0:0:0: [sda] 209715200 512-byte logical blocks: (107 GB/100 GiB)
[    7.624608] localhost kernel: sr 1:0:0:0: [sr0] scsi3-mmc drive: 4x/4x cd/rw xa/form2 tray
[    7.625103] localhost kernel: cdrom: Uniform CD-ROM driver Revision: 3.20
[    7.625957] localhost kernel: sd 0:0:1:0: [sdb] 204800 512-byte logical blocks: (104 MB/100 MiB)
[    7.626636] localhost kernel: sd 0:0:1:0: [sdb] Write Protect is off
[    7.627123] localhost kernel: sd 0:0:1:0: [sdb] Mode Sense: 00 3a 00 00
[    7.627142] localhost kernel: sd 0:0:1:0: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    7.636022] localhost kernel: sr 1:0:0:0: Attached scsi CD-ROM sr0
[    7.661168] localhost kernel:  sdb:
[    7.675269] localhost kernel: sd 0:0:0:0: [sda] Write Protect is off
[    7.675794] localhost kernel: sd 0:0:0:0: [sda] Mode Sense: 00 3a 00 00
[    7.676161] localhost kernel: sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    7.682491] localhost kernel: sd 0:0:1:0: [sdb] Attached SCSI disk
[    7.694045] localhost kernel: GPT:Primary header thinks Alt. header is not at the end of the disk.
[    7.699756] localhost kernel: GPT:2383871 != 209715199
[    7.700468] localhost kernel: GPT:Alternate GPT header not at the end of the disk.
[    7.701117] localhost kernel: GPT:2383871 != 209715199
[    7.702802] localhost kernel: GPT: Use GNU Parted to correct GPT errors.
[    7.703783] localhost kernel:  sda: sda1 sda2 sda3
[    7.715540] localhost kernel: sd 0:0:0:0: [sda] Attached SCSI disk
[    7.560598] localhost systemd[1]: Found device QEMU_HARDDISK ROOT.
[    7.600723] localhost systemd[1]: Starting File System Check on /dev/disk/by-uuid/a06ce38f-8ce2-4d01-b5f2-4b5a90bf2618...
[    7.630803] localhost systemd[1]: Started dracut initqueue hook.
[    7.642736] localhost systemd[1]: Starting dracut pre-mount hook...
[    7.674928] localhost systemd[1]: Reached target Remote File Systems (Pre).
[    7.723122] localhost systemd[1]: Reached target Remote File Systems.
[    7.733454] localhost systemd-fsck[1283]: ROOT: clean, 21022/73152 files, 218756/292091 blocks
[    7.756759] localhost systemd[1]: Started File System Check on /dev/disk/by-uuid/a06ce38f-8ce2-4d01-b5f2-4b5a90bf2618.
[    8.425207] localhost kernel: GPT:Primary header thinks Alt. header is not at the end of the disk.
[    8.430818] localhost kernel: GPT:2383871 != 209715199
[    8.431378] localhost kernel: GPT:Alternate GPT header not at the end of the disk.
[    8.432014] localhost kernel: GPT:2383871 != 209715199
[    8.432758] localhost kernel: GPT: Use GNU Parted to correct GPT errors.
[    8.433532] localhost kernel:  sda: sda1 sda2 sda3
[    8.112188] localhost systemd[1]: Stopped File System Check on /dev/disk/by-uuid/a06ce38f-8ce2-4d01-b5f2-4b5a90bf2618.
[    8.201176] localhost systemd[1]: Starting File System Check on /dev/disk/by-uuid/a06ce38f-8ce2-4d01-b5f2-4b5a90bf2618...
[    8.576217] localhost kernel: random: crng init done
[    8.268390] localhost systemd-fsck[1430]: ROOT: clean, 21022/73152 files, 218756/292091 blocks
[    8.286455] localhost systemd[1]: Started File System Check on /dev/disk/by-uuid/a06ce38f-8ce2-4d01-b5f2-4b5a90bf2618.
[    9.127467] localhost systemd[1]: Stopped File System Check on /dev/disk/by-uuid/a06ce38f-8ce2-4d01-b5f2-4b5a90bf2618.
[    9.150954] localhost dracut-pre-mount[1287]: The operation has completed successfully.
[    9.474741] localhost kernel:  sda: sda1 sda2 sda3
[    9.261760] localhost systemd[1]: Starting File System Check on /dev/disk/by-uuid/a06ce38f-8ce2-4d01-b5f2-4b5a90bf2618...
[    9.327416] localhost systemd-fsck[1443]: ROOT: clean, 21022/73152 files, 218756/292091 blocks
[    9.336511] localhost systemd[1]: Started File System Check on /dev/disk/by-uuid/a06ce38f-8ce2-4d01-b5f2-4b5a90bf2618.
[   10.676608] localhost kernel:  sda: sda1 sda2 sda3
[   10.360401] localhost systemd[1]: Stopped File System Check on /dev/disk/by-uuid/a06ce38f-8ce2-4d01-b5f2-4b5a90bf2618.
[   10.513512] localhost systemd[1]: Starting File System Check on /dev/disk/by-uuid/a06ce38f-8ce2-4d01-b5f2-4b5a90bf2618...
[   10.859154] localhost kernel:  sda: sda1 sda2 sda3
[   10.573349] localhost systemd-fsck[1493]: fsck.ext2: No such file or directory while trying to open /dev/disk/by-uuid/a06ce38f-8ce2-4d01-b5f2-4b5a90bf2618
[   10.573449] localhost systemd-fsck[1493]: Possibly non-existent device?
[   10.574337] localhost systemd[1]: Stopped File System Check on /dev/disk/by-uuid/a06ce38f-8ce2-4d01-b5f2-4b5a90bf2618.
[   10.708501] localhost systemd[1]: Starting File System Check on /dev/disk/by-uuid/a06ce38f-8ce2-4d01-b5f2-4b5a90bf2618...
[   10.772061] localhost systemd-fsck[1523]: ROOT: clean, 21022/73152 files, 218756/292091 blocks
[   10.781329] localhost systemd[1]: Started File System Check on /dev/disk/by-uuid/a06ce38f-8ce2-4d01-b5f2-4b5a90bf2618.
[   10.813238] localhost systemd[1]: Stopped File System Check on /dev/disk/by-uuid/a06ce38f-8ce2-4d01-b5f2-4b5a90bf2618.
[   11.157277] localhost kernel:  sda: sda1 sda2
[   11.023231] localhost systemd[1]: start request repeated too quickly for systemd-fsck-root.service
[   11.024385] localhost systemd[1]: Failed to start File System Check on /dev/disk/by-uuid/a06ce38f-8ce2-4d01-b5f2-4b5a90bf2618.
[   11.150436] localhost systemd[1]: Dependency failed for /sysroot.
[   11.175837] localhost systemd[1]: Dependency failed for Initrd Root File System.
[   11.189030] localhost systemd[1]: Dependency failed for Reload Configuration from the Real Root.
```

As you can see, the repartition repeatedly triggers systemd-fsck-root.service, until it finally fails.
(sdb is only a small additional blockdev attachted to the qemu to copy out the logs)

It might be more obvious on CentOS (probably the CentOS parted tools more often trigger a reread of the partition table or such), but I have seen spurious firstboot failures on SLES15 images also, which magically repaired themselves after a reboot but might be related.

More data points:
   * I could not reliably reproduce this behaviour on LVM images, but had reports of my users on spurious installation failures that were fixed with a reboot on CentOS7/LVM, also.
   * might be EFI / GPT related?

## Expected behaviour
The system resizes the file system and boots.

## Steps to reproduce the behaviour
See description above

## OS and Software information
+ KIWI version: git master
+ Operating system: openSUSE Leap 15, CentOS-7
+ OBS version: as on build.opensuse.org, but also happens on local build

### PR DESCRIPTION
**Pull request by seife**
See issue#1034, this fixes non-booting CentOS-7 OEM images that fail
during repartition / FS resize.
Summary: all parted actions trigger a rescan of partition tables and
this repeatedly starts / stops systemd-fsck-root.service until it
finally fails. The workaround is to mask systemd-fsck-root.service
during repartitioning / FS resize.

Fixes #1034

### CODE REVIEW

**Comment by schaefi** [comment]
This looks really nice :+1:

**Comment by schaefi** [comment]
Forget about the travis error, this is just stupid at the moment. We will fix this

**Comment by seife** [comment]
> 
> 
> Looks good so far, let me run some test. Thanks much!

I did check with CentOS-7 and SLES15.
Before, i tried things like
```
systemctl stop systemd-fsck-root
systemctl mask systemd-fsck-root
.....
....
systemctl unmask...
systemctl start...
```
To ensure that the fsck was really running. But this always failed on one or the other OS (systemctl start just hang on SLES15, but not on Centos...)
So I figured out that `systemctl mask` is enough, because, at least in my tries, the fsck had already run before the repartitioning is tried.

And, in the end, the FS is brand new, so even this causes the fsck to be accidentally skipped, it would do no harm IMHO.
I also tried additional boots of the installed system (without rebuilt initrd, so kiwi-* is still in, and it always started the fsck before the repart decided that it had nothing to do anymore.

Note that reproducing can be flaky. Maybe just looking for "some" tries to start fsck during resize (in the version before my patch) in journal is a good way to find out if you have just been lucky :-)

**Comment by schaefi** [comment]
I also tested and worked really great. The mask and umask commands where unknown to me too. I've learned something. Thanks much @seife :+1:

**Comment by schaefi** [comment]
a rebase of this to master will also fix the travis issues

**Comment by seife** [comment]
Comment updated

**Comment by schaefi** [comment]
great :+1:

**Pull request merged**
