### PR TITLE
Remove unneeded shebangs from dracut modules

### LINKED ISSUE #668: dracut module shell script files for kiwi-lib have shebangs when they shouldn't
## Problem description
In [the package review for kiwi for Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1483339), the following issue came up from @decathorpe:

> 8) dracut modules (in "/usr/lib/drac7t/modules.d/99kiwi-lib/*" have bash shebangs, but aren't marked as executable. Is that correct?

These files are purely functions and should not have shebangs, since there's nothing useful to execute.

## OS and Software information
+ KIWI version: 9.13.7
+ Operating system: Fedora 27

### PR DESCRIPTION
**Pull request by davidcassany**
This PR removes the shebang from some bash files that contain only functions, thus they are not executable (they are only sourced).

Fixes #668

### CODE REVIEW

**Comment by davidcassany** [comment]
@schaefi, what you think about this change? I am not very happy about having to force the shell type in the shellcheck call, but after thinking about it I thought that probably this is the best solution. Another option would be to make all these files executable but I think it would just be worse.

**Comment by schaefi** [comment]
I think it does not hurt but I guess apart from the adaption to the code and the shellcheck call there will be also rpmlint complaining about the missing shebang. Have you tried building an rpm package and check the rpmlint output ?

Apart from all that I wonder about the motivation for the change ? Did the shebangs cause any trouble elsewhere ?

Of course deleting code is always nice, thus if it does not cause us trouble I'm fine with the change :)

**Comment by davidcassany** [comment]
> I think it does not hurt but I guess apart from the adaption to the code and the shellcheck call there will be also rpmlint complaining about the missing shebang. Have you tried building an rpm package and check the rpmlint output ?

This is a good point, I'll check. I assumed it would not complain since the whole idea behind is to minimize rpmlint complaints.

> Apart from that I wonder about the motivation for the change ? Did the shebangs cause any trouble elsewhere ?

Apparently in Fedora tool chain this causes rpmlint issues. If a shebang is there in a file it expects the executable attribute. See #666 comments (also the link with the package review is nice).

**Comment by schaefi** [comment]
ah ok, thanks for the update. So if the suse package build is good to go I'm fine

**Comment by davidcassany** [comment]
All right, it has no impact on our packages. I saw that had a warning on `kiwi/config/functions.sh` for the same reason, so I applied the same criteria and now we got rid of a couple of warnings. Also removed the rpmlint filter to ignore non-executable-script warnings in dracut modules.

**Comment by schaefi** [comment]
great :+1:

**Pull request merged**
