### PR TITLE
Update spec file to require xorriso

### PR DESCRIPTION
**Pull request by schaefi**
Hope it can be done that way for all distros

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@schaefi It is the `xorriso` package in Fedora, EPEL (for CentOS/RHEL), Mageia, and Debian/Ubutnu.

**Comment by schaefi** [comment]
thank you guys for checking it :+1:

**Comment by DimStar77** [comment]
Xorriso is actuall very expensive, as xorriso requires /usr/bin/wish, which is provided by tk, and that in turn requires tcl.

(I had to unblock tk/tcl for the live images for now)

**Comment by DimStar77** [comment]
And fedora counts as error free reference since when?

**Comment by Conan-Kudo** [comment]
@DimStar77 So either delete it, or subpackage it out.

**Comment by DimStar77** [comment]
No kidding... What would I do without such an advise. I would be lost. Thanks!!! 
(And yes, splitting is the best course here)

**Comment by Conan-Kudo** [comment]
Sorry, I'm just incredibly frustrated, annoyed, and stressed because of https://github.com/openSUSE/open-build-service/issues/4761 completely screwing up my week.

**Pull request merged**
