### PR TITLE
Leap 15

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by schaefi** [comment]
@lnussel Thanks, just for my own understanding suse-leap15.0 is not the same as suse-SLES15 which already exists, meaning leap15.0 is a different distro than SLES15, correct ?

**Comment by lnussel** [comment]
yes, just like leap 42 vs sle 12

**Comment by lnussel** [comment]
so, ok to merge?

**Comment by schaefi** [comment]
ok thanks

**Pull request merged**
