### PR TITLE
Added support for system wide config file

### PR DESCRIPTION
**Pull request by schaefi**
If there is no user specific config file we are also
looking for a system wide /etc/kiwi.yml file

### CODE REVIEW

**Comment by schaefi** [comment]
We need this to allow using a config file inside of the obs buildservice. The environment there does not populate a user thus there is no "home" and you won't be able to provide user specific data

**Comment by schaefi** [comment]
I'd like to continue testing this in the pubcloud builds and need to go ahead merging it. If you see issues just let me know and we address them in a follow up request. Thanks

**Comment by davidcassany** [comment]
@schaefi, sure no problem, having a look now. Also if you are in rush and I can help you in some way let me know.

**Comment by schaefi** [comment]
Thanks for the after merge review :) I wanted to fix that while my pubcloud team was still at work, which was a night session at my place but that's ok we solved it

> how are you providing the configuration file in the build service. Using specific RPM that provides it

yes if you look at:

Devel:PubCloud/kiwi-sle12-config

you will find a package kiwi_sle12_config which provides an /etc/kiwi.yml

In the projconf of the project Devel:PubCloud:GoogleCompute:ImagesSLE124P
you see the following entries:

preinstall: kiwi_sle12_config
Ignore: python3-kiwi:xorriso

which allows me to place the kiwi.yml into the worker before kiwi starts and overwrites the xorriso requirement of the latest kiwi version we want to use in the Devel space for sles12. sles12 does
not provide any xorriso and the config file switches the iso tool_category back to cdrtools

**Comment by schaefi** [comment]
The kiwi version we submit to sle12 SP4 officially is from our branch and there we have changed the default iso tool setup to match the distro but for building pubcloud images in Devel we want to use the latest version of kiwi and port required features to sles12 as we see fit

**Pull request merged**
