### PR TITLE
Added build of python-kiwi for Debian based distro

### PR DESCRIPTION
**Pull request by schaefi**
This is a first step to also build the kiwi project for
Debian based distros. However so far this only builds
the dracut module packages as those are required for
Debian builds on non Debian based build hosts. In the
long run this package setup should be extended to have
kiwi fully packaged for Debian

### CODE REVIEW

**Comment by schaefi** [comment]
my deb skills are limited, so forgive me if there is anything stupid in here :)

**Comment by Conan-Kudo** [comment]
It's possible to build for Debian targets using the spec file instead of maintaining two different sets of packaging. I do this for many of the projects I work. As an example: https://github.com/datto/dattobd/blob/master/dist/dattobd.spec

@schaefi If you're interested in this, I can prepare a PR that does this for you. :)

**Comment by schaefi** [comment]
>  If you're interested in this, I can prepare a PR that does this for you. :)

@Conan-Kudo this would be super super cool if you could do that. Thanks much

**Comment by schaefi** [comment]
@Conan-Kudo do you still plan to help us out here ? so I can close this pull request ?

would be really great, thanks

**Comment by Conan-Kudo** [comment]
@schaefi I am working on it, so if you'd like to close this, go ahead.

**Comment by schaefi** [comment]
closing, #618 is the way better approach to do this :)

**Pull request closed without merging**
