### PR TITLE
Checkmedia results and plymouth

### PR DESCRIPTION
**Pull request by schaefi**
Improve display of runMediaCheck results
    
The splash screen should be switched off in order to let the
user see the mediacheck results as well as a delay timeout
before the boot continues or stops is useful

### CODE REVIEW

**Comment by DimStar77** [comment]
From reading the PR (no media tested with it yet) this seems to do exactly what I'd like it to do

**Comment by schaefi** [comment]
ok, thanks. @davidcassany would you mind to double check my code changes ? I have done some tests but another user experience would be good. Thanks

**Comment by schaefi** [comment]
I could not resist to make this nicer and use a dialog based session called by systemd now. plymouth got disabled for mediacheck now as ist stands in our way when we want to display information

second review is appreciated :)

**Comment by Conan-Kudo** [comment]
@schaefi As an aside though, you could have actually had all of this rendered through Plymouth. It's possible to at least print the messages through Plymouth, rather than having to disable the splash entirely. As for the dialog box, I *think* there's a way, but I'm not sure.

**Comment by schaefi** [comment]
I tried it but had some trouble, especially if there is no framebuffer which could happen. I also had trouble with interaction, all input is taken by plymouth and I could not navigate the dialog it offers. I did not want to dive deeper and just used a safe default with console tools

**Pull request merged**
