### PR TITLE
Add clear attribute for entrypoint and subcommand sections

### PR DESCRIPTION
**Pull request by davidcassany**
This commit adds the possibility of clearing any subcommand or
entrypoint. This is relevant for docker derived images, as they
inherit the configuration and it might lead to some bad behavior.

See how it is used [here](https://github.com/davidcassany/kiwi-derived-images)

### CODE REVIEW

**Comment by schaefi** [comment]
:+1: thanks 

I was worrying if the name of the attribute is kind of self explaining but the docker tooling uses the same option name so I think it's ok to go with it

**Comment by schaefi** [comment]
One thing I noticed was that the schema docs was not updated regarding the schema change

**Comment by davidcassany** [comment]
@schaefi you are absolutely right, I forgot to re run the docs generator, I will include it

**Comment by davidcassany** [comment]
@schaefi, now should be fine

**Comment by schaefi** [comment]
yep, thanks

**Pull request merged**
