### PR TITLE
Fix arm test

### PR DESCRIPTION
**Pull request by davidcassany**
In this PR:

* Included openSUSE:Factory/ports repository

### CODE REVIEW

**Comment by davidcassany** [comment]
@schaefi integration test in the OBS is pulling from that branch, since the build was blocked a couple of days ago I did not want to start making commits to master in a trial error fashion, thus I separated in this branch. 

The problem is that I can't test it locally as I did with the x86 tests before committing, thus a new branch looked like the way to go.

**Comment by schaefi** [comment]
Hmm, Virtualization:Appliances:Images:Testing_arm/test-image-panda-oem is in state

* succeeded

Are you sure we need this change ?

**Comment by schaefi** [comment]
Oh now I see it the _service is referencing to fix_arm_test branch
nevermind

**Comment by schaefi** [comment]
With the switch to dracut the hook tarball is no longer needed. With this PR it would come back unused. So you can safely delete that commit

**Comment by davidcassany** [comment]
Yes in fact you are right, I included it not to break the _service which was trying to extract it, but I did not realize it shouldn't be there as it is not even included in the packages section.

**Comment by davidcassany** [comment]
just waiting for the test to be succeeded again and we'll be done here.

**Comment by davidcassany** [comment]
now the test is green again, the _service file does not try to pull the uboot hooks and the repositories are well defined only within the appliance.kiwi file.

This is ready to merge to my eyes.

**Comment by schaefi** [comment]
yes, thanks 👍

**Pull request merged**
