### PR TITLE
Rearrange & Restructure Quick Start

### LINKED ISSUE #319: Rearrange and Restructure Quick Start
## Problem description
As we all know, users don't want to read too much or too complicated stuff. Additionally, the documentation should be presented in a way, that it makes it easy to follow it. As we know, users are impatient and want results NOW.

After looking at the Quick Start, I think, it doesn't serve this idea well. IMHO. I see the following issues with the current content:

* It does not contain step-by-step instructions to guide the user.
* Although compatibility is an important topic, it isn't something a Quick Start should deal with. IMHO this is a topic which belongs to another chapter.
* The Quick Start doesn't distinguish between concepts (background information, design etc.) and procedural information (target, step-by-step instructions)
* It's not clear what the goal is.
* Too many options ("Using KIWI NG from Build Service" vs. "Using KIWI NG in a Python Project"); 

## Proposed Solution
The Quick Start should answer the following questions:

* **What is our target group?**
  Developers or users who aren't familiar with the concept yet. The are impatient and want results NOW.
* **What's the aim for the Quick Start?**
  Help the user to get a success story quickly! 😄
* **How to do it?**
  * Give users steps to guide them so they can follow them quickly.
  * Distinguish between concept and procedural information in headers by using nouns and verbs

WIth the previous ideas in mind, I would propose to rearrange and restructure the information in the Quick Start as follows (draft):

```
KIWI Quick Start: Building an Image
   1. Usage Scenario
       Lays the foundation of the topic, describes what the user will get
   2. System Requirements
       States what is required when you use this guide
   3. Basic Workflow
       Describes the concept of KIWI
   4. Installing KIWI
       Gives instructions on what the user has to do when installing KIWI.
   5. Building an Image
       Gives step-by-step instructions on what the user needs to execute
   6. Using Additional Example Appliance Descriptions
       Shows some additional usage, extending the basic usage in section 5.
```

The above structure is certainly not perfect, but it will give you a good impression. Probably it has to be shifted here and there to make it work. Maybe, we should move some content ("Basic Workflow") to a different location.

Lot of the above sections can be filled with the content we already have. The task would be to group and rearrange them accordingly to fit the proposed idea in this issue.

@davidcassany, @schaefi Comments? Thoughts? 😄

### PR DESCRIPTION
**Pull request by tomschr**
Fixes #319

Changes proposed in this pull request:

* Completely revamp structure
* Define terms in a terminology list
* Distinguish between concept (headings have nouns) and procedures/actions (headings start with a verb)
* Add FIXMEs and TODOs for David ;)
* Overall goal: make it short (the "quick" in Quick Start) and leave the details to other guides/chapters

### CODE REVIEW

**Comment by schaefi** [comment]
Thanks much for your effort. Regarding our e-mail communication I think I want to restructure the docs a little bit more and then include your changes from this pull request. Would you mind to give me a day or two to come up with a suggestion :) Thanks

**Comment by schaefi** [comment]
I have added your work in the doc_redesign branch and hope it was ok doing so. Due to the restructuring I have moved the changes into several files: overview, installation, quickstart

Feel free to perform further modifications in the doc_redesign branch and if you think all information is in place I think this one can be closed.

Thanks and sorry if we created a little conflict ;)

**Comment by tomschr** [comment]
Oh, great! 👍 Thanks a lot! And no worries! :wink:

I will have a look in the doc_redesign branch and will give you a notice.

Thanks for your efforts!

**Comment by tomschr** [comment]
@schaefi wow, your restructuring was even better! 👍 I like the first start, great!

Not sure if we should discuss further ideas here or at another place (mail, separate issue?)

**Comment by schaefi** [comment]
I think we've covered the next steps by mail. The changes provided here are part of the doc_redesign branch as you have checked out and send feedback for. Thanks much I think we can close this one

**Pull request closed without merging**
