### PR TITLE
Complete test coverage on iso tools testing

### PR DESCRIPTION
**Pull request by schaefi**
If there is no mkisofs/genisoimage present on the system, the
tests based on real example iso files are skipped. The code
tested in this case is now covered in a mock style to run
through the logic even without the tools in place

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Does it run proper tests if xorriso is installed?

**Comment by schaefi** [comment]
sure, on xorriso all of this header magic is not required. So the tests for the xorriso code are complete too but different. Out of scope for this one here I would say

**Comment by dcermak** [comment]
@schaefi Let me cherry-pick your commit and test it in #980 so that we see whether gitlab works with that.

**Comment by schaefi** [comment]
yep thanks it should be all green after the cherry-pick

**Comment by dcermak** [comment]
> yep thanks it should be all green after the cherry-pick

Gitlab is happy: https://gitlab.com/D4N/kiwi-ci/pipelines/50713849, so feel free to merge this.

**Pull request merged**
